name: V2-Clash Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set git user name
      run: git config --global user.name "GitHub Actions"

    - name: Set git user email
      run: git config --global user.email "actions@github.com"

    - name: Checkout code
      uses: actions/checkout@v2

    # Rest of the workflow steps
