name: Secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secrets
        env:
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
          echo "NAME=${{ secrets.NAME }}" >> $GITHUB_ENV
